export const mapPropertyVMtoApi = property => ({
    id: property.id,
    title: property.title,
    notes: property.notes,
    email: property.email,
    phone: property.phone,
    price: Number(property.price),
    saleTypesIds: property.saleTypes,
    address: property.address,
    city: property.city,
    provinceId: property.province,
    squareMeter: Number(property.squareMeter),
    rooms: Number(property.rooms),
    bathrooms:Number(property.bathrooms),
    locationUrl: property.locationUrl,
    mainFeatures: property.mainFeatures,
    equipmentIds: property.equipments,
    images: property.images,
    });
